use_frameworks!

def shared_testKits
    pod 'Quick'
    pod 'Nimble'
end

target 'XXShield_Example' do
  platform :ios, '8.0'
  pod 'XXShield', :path => '../'

  target 'XXShield_Tests' do
    inherit! :search_paths
    shared_testKits
  end
end

target 'XXShield_OSX_Example' do
    platform :osx, '10.10'
    pod 'XXShield', :path => '../'

    target 'XXShield_OSX_Tests' do
        inherit! :search_paths
        shared_testKits
    end
end
